// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYTwrFhJ2g9ZP1HOSQmzYNQtcdZHXoGg',
    appId: '1:838625178343:web:ff0a2dd77f35b4f4aae842',
    messagingSenderId: '838625178343',
    projectId: 'news-app-e526e',
    authDomain: 'news-app-e526e.firebaseapp.com',
    storageBucket: 'news-app-e526e.appspot.com',
    measurementId: 'G-S711CW7RHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz0DA1l3a7Oo0_lfeQaPHgFTwlH-jRGQA',
    appId: '1:838625178343:android:b3d80270990f7642aae842',
    messagingSenderId: '838625178343',
    projectId: 'news-app-e526e',
    storageBucket: 'news-app-e526e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvgtiRlg5fRlTowof6i7i5gx8iNCezkkE',
    appId: '1:838625178343:ios:c27a3f818598dff8aae842',
    messagingSenderId: '838625178343',
    projectId: 'news-app-e526e',
    storageBucket: 'news-app-e526e.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvgtiRlg5fRlTowof6i7i5gx8iNCezkkE',
    appId: '1:838625178343:ios:d3b23173a5ba29c1aae842',
    messagingSenderId: '838625178343',
    projectId: 'news-app-e526e',
    storageBucket: 'news-app-e526e.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
